# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2816831151d2d6134853d43f1f9e50b95dc349b2be9649402c6c550a0643ca1434daa619f6ee702beac4a065205b4f742b3edddd79569a6a6cc57888e8286b6

test:
  secret_key_base: c4771484194fcaa6b9e21b27870fdcb587f0b0e11ae10609afc333235a07144cd771941dc926d5efe413d496a534cfb642271964ee24a848ff6574bc9ff795d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
